name: Sultan

permissions:
  contents: write
  actions: write

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    paths-ignore:
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kernel:
          - codename: gs201
            repo: "android_kernel_google_gs201"
            android_version: "android14"
            kernel_version: "6.1"
            defconfig: gs201_defconfig
            local_version: "-android14-11-g66e758f7d0c0-ab13748739"
            build_date: "Tue Jul  8 09:17:32 UTC 2025"
        build:
#          - type: Normal
#            ksu: false
#            ak3_suffix: ""
          - type: KSU
            ksu: true
            repo: "tiann/KernelSU"
            folder: "KernelSU"
            branch: "main"
            kernel_patches: "../james_patches/next/next_hooks.patch"
            extra_configs: "CONFIG_KPROBES=n"
            susfs_patch: "../susfs/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch"
            ak3_suffix: "_KSU"
          - type: KSUN
            ksu: true
            repo: "KernelSU-Next/KernelSU-Next"
            folder: "KernelSU-Next"
            branch: "next"
            susfs_repo: "pershoot/KernelSU-Next"
            susfs_branch: "next-susfs"
            ksu_patches: "KSUN/WildJames-Manager.patch"
            kernel_patches: "../james_patches/sultan/syscall_hooks.patch"
            extra_configs: "CONFIG_KSU_KPROBES_HOOK=n"
#            susfs_patch: "sultan/KSUN/KSUN-SUSFS-1.5.12.patch"
            ak3_suffix: "_KSUNext"
          - type: RKSU
            ksu: true
            repo: "rsuntk/KernelSU"
            folder: "KernelSU"
            branch: "main"
            susfs_branch: "susfs-main"
            kernel_patches: "../james_patches/sultan/syscall_hooks.patch"
            extra_configs: "CONFIG_KSU_MANUAL_HOOK=y"
#            susfs_patch: "sultan/RKSU/RKSU-SUSFS-1.5.12.patch"
            ak3_suffix: "_RKSU"
          - type: SukiSU
            ksu: true
            repo: "SukiSU-Ultra/SukiSU-Ultra"
            folder: "KernelSU"
            branch: "nongki"
            susfs_branch: "susfs-main"
            ksu_patches: "../fix_list_count_nodes_indent.patch"
            kernel_patches: "../james_patches/sultan/syscall_hooks.patch"
            extra_configs: "CONFIG_KSU_MANUAL_HOOK=y CONFIG_KSU_MANUAL_SU=n CONFIG_COMPAT=y CONFIG_ZRAM_GS_WRITEBACK=y"
            ak3_suffix: "_SukiSU"
            # kpm: "https://raw.githubusercontent.com/ShirkNeko/SukiSU_patch/refs/heads/main/kpm/patch_linux"

        susfs: [false, true]
        exclude:
          - build:
              ksu: false
            susfs: true

    steps:
      - name: Download and extract GCC 14.2.0 toolchain
        run: |
          echo "Downloading GCC 14.2.0 cross-compiler toolchain..."
          wget https://www.kernel.org/pub/tools/crosstool/files/bin/x86_64/14.2.0/x86_64-gcc-14.2.0-nolibc-aarch64-linux.tar.gz -O gcc.tar.gz
          echo "Extracting .gz file..."
          gunzip gcc.tar.gz
          echo "Extracting .tar file..."
          tar -xf gcc.tar
          echo "GCC 14.2.0 toolchain extracted successfully"

      - name: Clone Dependencies and set ENV
        run: |
          ANYKERNEL_BRANCH="sultan-${{ matrix.kernel.codename }}"
          SUSFS_BRANCH="gki-${{ matrix.kernel.android_version }}-${{ matrix.kernel.kernel_version }}"

          sudo apt-get install -y --no-install-recommends ccache
          ccache --max-size=2G
          ccache --set-config=compression=true
          echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV

          git clone --depth=1 https://github.com/TheWildJames/AnyKernel3.git -b "$ANYKERNEL_BRANCH" AK3
          echo "ak3_dir=$PWD/AK3" >> $GITHUB_ENV
          git clone --depth=5 https://gitlab.com/simonpunk/susfs4ksu.git -b "$SUSFS_BRANCH" susfs
          echo "susfs_dir=$PWD/susfs" >> $GITHUB_ENV
          git clone --depth=1 https://github.com/TheWildJames/kernel_patches.git james_patches
          echo "james_dir=$PWD/james_patches" >> $GITHUB_ENV
          git clone --depth=1 https://github.com/kerneltoast/${{ matrix.kernel.repo }} sultan
          echo "kernel_dir=$PWD/sultan" >> $GITHUB_ENV
          git clone --depth=1 https://github.com/TheSillyOk/kernel_ls_patches ok_patches
          echo "ok_dir=$PWD/ok_patches" >> $GITHUB_ENV
          curl "https://gist.githubusercontent.com/MiRinChan/87371b65f283bb031d80e55b16b6d7ad/raw/6b82ef649188c1f0f593b0cd8a5146c5e4fd0114/fix_list_count_nodes_indent.patch" > fix_list_count_nodes_indent.patch

          ${{ matrix.susfs || false }} && ksu_repo="${{ matrix.build.susfs_repo || matrix.build.repo }}" || ksu_repo="${{ matrix.build.repo }}" || true
          echo "ksu_repo=$ksu_repo" >> $GITHUB_ENV
          ${{ matrix.susfs || false }} && ksu_branch="${{ matrix.build.susfs_branch || matrix.build.branch }}" || ksu_branch="${{ matrix.build.branch }}" || true
          echo "ksu_branch=$ksu_branch" >> $GITHUB_ENV

          build_type="${{ matrix.build.ak3_suffix }}"
          ${{ matrix.susfs }} && build_type="$build_type.SUSFS" || true
          date=$(date +"%d.%m.%Y")
          zip_name="$date-${{ matrix.kernel.codename }}${build_type}_A16_Sultan-${{ github.run_number }}"
          echo "zip_name=$zip_name" >> $GITHUB_ENV

      - name: Setup kernel stuff
        run: |
          cd "${{ env.kernel_dir }}"

          if [[ -n "${{ matrix.build.kernel_patches }}" ]]; then
            for patch_name in ${{ matrix.build.kernel_patches }}; do
              patch -p1 -F 3 < "${{ env.ok_dir }}/${patch_name}"
            done
          fi

          configs="CONFIG_TMPFS_XATTR=y CONFIG_TMPFS_POSIX_ACL=y CONFIG_IP_NF_TARGET_TTL=y CONFIG_IP6_NF_TARGET_HL=y CONFIG_IP6_NF_MATCH_HL=y CONFIG_TCP_CONG_ADVANCED=y CONFIG_TCP_CONG_BBR=y CONFIG_NET_SCH_FQ=y CONFIG_TCP_CONG_BIC=n CONFIG_TCP_CONG_WESTWOOD=n CONFIG_TCP_CONG_HTCP=n  CONFIG_DEFAULT_BBR=y CONFIG_BPF_STREAM_PARSER=y CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y CONFIG_NETFILTER_XT_SET=y CONFIG_IP_SET=y CONFIG_IP_SET_MAX=65534 CONFIG_IP_SET_BITMAP_IP=y CONFIG_IP_SET_BITMAP_IPMAC=y CONFIG_IP_SET_BITMAP_PORT=y CONFIG_IP_SET_HASH_IP=y CONFIG_IP_SET_HASH_IPMARK=y CONFIG_IP_SET_HASH_IPPORT=y CONFIG_IP_SET_HASH_IPPORTIP=y CONFIG_IP_SET_HASH_IPPORTNET=y CONFIG_IP_SET_HASH_IPMAC=y CONFIG_IP_SET_HASH_MAC=y CONFIG_IP_SET_HASH_NETPORTNET=y CONFIG_IP_SET_HASH_NET=y CONFIG_IP_SET_HASH_NETNET=y CONFIG_IP_SET_HASH_NETPORT=y CONFIG_IP_SET_HASH_NETIFACE=y CONFIG_IP_SET_LIST_SET=y CONFIG_IP6_NF_NAT=y CONFIG_IP6_NF_TARGET_MASQUERADE=y"
          if [[ -n "${{ matrix.build.extra_configs }}" ]]; then
            configs="$configs ${{ matrix.build.extra_configs }}"
          fi

          for config in $configs; do
            echo "--> Added ${config} <--"
            config_name=$(echo "${config}" | cut -d "=" -f 1)
            sed -i -E 's/.*($config_name=.*)/# \1/gi' ${{ env.kernel_dir }}/arch/arm64/configs/${{ matrix.kernel.defconfig }}
            echo -e "\n${config}" >> "${{ env.kernel_dir }}/arch/arm64/configs/${{ matrix.kernel.defconfig }}"
          done

          sed -i 's/${LOCALVERSION+set}/set/' ${{ env.kernel_dir }}/scripts/setlocalversion
          sed -i 's/CONFIG_LOCALVERSION="-Sultan"/CONFIG_LOCALVERSION="${{ matrix.kernel.local_version }}"/' ${{ env.kernel_dir }}/arch/arm64/configs/${{ matrix.kernel.defconfig }}
          perl -pi -e 's/build-timestamp = \$\(or \$\(KBUILD_BUILD_TIMESTAMP\), \$\(build-timestamp-auto\)\)/build-timestamp = "${{ matrix.kernel.build_date }}"/' ${{ env.kernel_dir }}/init/Makefile

      - name: Add KernelSU (${{ matrix.build.type }})
        if: matrix.build.ksu
        run: |
          cd "${{ env.kernel_dir }}"

          echo "Adding KernelSU..."
          curl -LSs "https://raw.githubusercontent.com/${{ env.ksu_repo }}/${{ env.ksu_branch }}/kernel/setup.sh" | bash -s ${{ env.ksu_branch }}
          if [[ -n "${{ matrix.build.checkout }}" ]]; then
            cd "${{ matrix.build.folder }}" && git checkout "${{ matrix.build.checkout }}" && cd -
          fi

          if [[ -n "${{ matrix.build.ksu_patches }}" ]]; then
            cd "${{ matrix.build.folder }}"
            for patch_name in ${{ matrix.build.ksu_patches }}; do
              patch -p1 < "${{ env.ok_dir }}/${patch_name}"
            done
            cd "${{ env.kernel_dir }}"
          fi

          # Add KSU configuration settings
          echo "CONFIG_KSU=y" >> ${{ env.kernel_dir }}/arch/arm64/configs/${{ matrix.kernel.defconfig }}
          echo "CONFIG_KSU_KPROBES_HOOK=n" >> ${{ env.kernel_dir }}/arch/arm64/configs/${{ matrix.kernel.defconfig }}

      - name: Apply SUSFS Patches
        if: matrix.susfs
        run: |

          # Copy SUSFS patches
          cp ${{ env.susfs_dir }}/kernel_patches/50_add_susfs_in_gki-${{ matrix.kernel.android_version }}-${{ matrix.kernel.kernel_version }}.patch ${{ env.kernel_dir }}/
          cp ${{ env.susfs_dir }}/kernel_patches/fs/* ${{ env.kernel_dir }}/fs/
          cp ${{ env.susfs_dir }}/kernel_patches/include/linux/* ${{ env.kernel_dir }}/include/linux/

          if [[ -n "${{ matrix.build.susfs_patch }}" ]]; then
            cd "${{ env.kernel_dir }}/${{ matrix.build.folder }}"
            patch -p1 --forward < ${{ env.ok_dir }}/${{ matrix.build.susfs_patch }}
          fi

          cd "${{ env.kernel_dir }}"
          patch -p1 < 50_add_susfs_in_gki-${{ matrix.kernel.android_version }}-${{ matrix.kernel.kernel_version }}.patch || true
          patch -p1 --fuzz=3 < ${{ env.james_dir }}/sultan/sys.c_fix.patch

          # Add SUSFS configuration settings
          echo "CONFIG_KSU_SUSFS=y" >> ${{ env.kernel_dir }}/arch/arm64/configs/${{ matrix.kernel.defconfig }}
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> ${{ env.kernel_dir }}/arch/arm64/configs/${{ matrix.kernel.defconfig }}
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ${{ env.kernel_dir }}/arch/arm64/configs/${{ matrix.kernel.defconfig }}

      - name: Cache Kernel Build
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ matrix.kernel.codename }}-${{ matrix.build.type }}-SUSFS_${{ matrix.susfs }}-ccache-${{ github.sha }}-${{ github.run_number }}
          restore-keys: |
            ${{ matrix.kernel.codename }}-${{ matrix.build.type }}-SUSFS_${{ matrix.susfs }}-ccache-
            ${{ matrix.kernel.codename }}-${{ matrix.build.type }}-
            ${{ matrix.kernel.codename }}-

      - name: Build the Kernel
        run: |
          cd "${{ env.kernel_dir }}"

          export KBUILD_BUILD_USER="TheSillyOk"
          export KBUILD_BUILD_HOST="Github"

          make CROSS_COMPILE=$GITHUB_WORKSPACE/gcc-14.2.0-nolibc/aarch64-linux/bin/aarch64-linux- CC=$GITHUB_WORKSPACE/gcc-14.2.0-nolibc/aarch64-linux/bin/aarch64-linux-gcc -j$(nproc --all) ${{ matrix.kernel.defconfig }}
          make CROSS_COMPILE="ccache $GITHUB_WORKSPACE/gcc-14.2.0-nolibc/aarch64-linux/bin/aarch64-linux-" CC="ccache $GITHUB_WORKSPACE/gcc-14.2.0-nolibc/aarch64-linux/bin/aarch64-linux-gcc" -j$(nproc --all)

      - name: Setup AnyKernel3 zip and KPM
        run: |
          cd "${{ env.kernel_dir }}"

          echo "Copying Image.lz4 and concatenating DTB files..."
          cp ./out/arch/arm64/boot/Image.lz4 ${{ env.ak3_dir }}/Image.lz4
          cat ./out/google-devices/${{ matrix.kernel.codename }}/dts/*.dtb > ${{ env.ak3_dir }}/dtb

          if [[ -n "${{ matrix.build.kpm }}" ]]; then
            cd ${{ env.ak3_dir }}
            curl -LSs "${{ matrix.build.kpm }}" -o patch && chmod 777 patch
            img_file=$(find . -type f -name "Image"* -maxdepth 1)
            echo "$img_file"

            # Decompress the kernel image if it's compressed
            if [[ "$img_file" == "./Image.gz"* ]]; then
              dd if="$img_file" bs=1 | gunzip > Image || true
              echo "-> Convert to: Image"
            elif [[ "$img_file" == "./Image.lz4" ]]; then
              lz4 -d "$img_file" Image
              echo "-> Decompress to: Image"
            fi

            ./patch && mv oImage Image

            # Re-compress the kernel image to its original format
            if [[ "$img_file" == "./Image.gz"* ]]; then
              gzip -c Image > Image.gz
              rm Image
              echo "-> Compress: Image.gz"
              # Special handling for images with appended DTB
              if [[ "$img_file" == "./Image.gz-dtb" ]]; then
                compressed_length=$(dd if=Image.gz-dtb bs=1 $skip | gzip -c | wc -c)
                dd if=Image.gz-dtb bs=1 skip=$compressed_length > dtb
                cat Image.gz dtb > Image.gz-dtb
                rm Image.gz && rm dtb
                echo "-- Image.gz -> Image.gz-dtb"
              fi
            elif [[ "$img_file" == "./Image.lz4" ]]; then
              lz4 -f Image Image.lz4
              rm Image
              echo "-> Compress: Image.lz4"
            fi

            rm patch
            cd -
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.zip_name }}
          path: ${{ env.ak3_dir }}/*
